import { fonts } from "./fonts";

export const typography = [
  {
    name: "H1",
    usage: "Page / Screen Title",
    size: "32px",
    weight: "Bold",
    lineHeight: "1.2",
    className: "ds-type-h1",
    fontFamily: fonts.bold,
  },
  {
    name: "H2",
    usage: "Section Title",
    size: "24px",
    weight: "SemiBold",
    lineHeight: "1.3",
    className: "ds-type-h2",
    fontFamily: fonts.semiBold,
  },
  {
    name: "H3",
    usage: "Card / Module Title",
    size: "20px",
    weight: "SemiBold",
    lineHeight: "1.3",
    className: "ds-type-h3",
    fontFamily: fonts.semiBold,
  },
  {
    name: "H4",
    usage: "Subheading",
    size: "16px",
    weight: "Medium",
    lineHeight: "1.4",
    className: "ds-type-h4",
    fontFamily: fonts.medium,
  },
  {
    name: "Body Large",
    usage: "Important content",
    size: "16px",
    weight: "Regular",
    lineHeight: "1.6",
    className: "ds-type-body-large",
    fontFamily: fonts.regular,
  },
  {
    name: "Body Medium",
    usage: "Body text",
    size: "14px",
    weight: "Regular",
    lineHeight: "1.6",
    className: "ds-type-body-medium",
    fontFamily: fonts.regular,
  },
  {
    name: "Body Small",
    usage: "Supporting text",
    size: "13px",
    weight: "Regular",
    lineHeight: "1.6",
    className: "ds-type-body-small",
    fontFamily: fonts.regular,
  },
  {
    name: "Caption",
    usage: "Labels, meta text",
    size: "11px",
    weight: "Regular",
    lineHeight: "1.4",
    className: "ds-type-caption",
    fontFamily: fonts.regular,
  },
] as const;
